import { db } from '@/db';
import { appointments } from '@/db/schema';

async function main() {
    const currentTimestamp = new Date().toISOString();
    
    const sampleAppointments = [
        {
            tenantId: 1,
            serviceId: 1,
            staffId: 1,
            customerId: null,
            guestName: 'Jane Smith',
            guestEmail: 'jane@email.com',
            guestPhone: '+1555000001',
            startTime: '2024-02-15T10:00:00.000Z',
            endTime: '2024-02-15T11:00:00.000Z',
            status: 'PENDING',
            notes: 'First-time customer',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            tenantId: 2,
            serviceId: 2,
            staffId: 2,
            customerId: null,
            guestName: 'Robert Brown',
            guestEmail: 'robert@email.com',
            guestPhone: '+1555000002',
            startTime: '2024-02-16T14:00:00.000Z',
            endTime: '2024-02-16T15:30:00.000Z',
            status: 'PENDING',
            notes: 'Needs relaxation massage',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            tenantId: 1,
            serviceId: 1,
            staffId: 1,
            customerId: null,
            guestName: 'Alice Williams',
            guestEmail: 'alice@email.com',
            guestPhone: '+1555000003',
            startTime: '2024-02-17T09:00:00.000Z',
            endTime: '2024-02-17T10:30:00.000Z',
            status: 'CONFIRMED',
            notes: 'Regular customer',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            tenantId: 3,
            serviceId: 3,
            staffId: 3,
            customerId: null,
            guestName: 'David Lee',
            guestEmail: 'david@email.com',
            guestPhone: '+1555000004',
            startTime: '2024-02-18T11:00:00.000Z',
            endTime: '2024-02-18T12:00:00.000Z',
            status: 'CONFIRMED',
            notes: 'Checkup appointment',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            tenantId: 2,
            serviceId: 2,
            staffId: 2,
            customerId: null,
            guestName: 'Emma Davis',
            guestEmail: 'emma@email.com',
            guestPhone: '+1555000005',
            startTime: '2024-02-14T16:00:00.000Z',
            endTime: '2024-02-14T17:00:00.000Z',
            status: 'CANCELLED',
            notes: 'Customer cancelled',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            tenantId: 1,
            serviceId: 1,
            staffId: 1,
            customerId: null,
            guestName: 'Chris Wilson',
            guestEmail: 'chris@email.com',
            guestPhone: '+1555000006',
            startTime: '2024-02-13T13:00:00.000Z',
            endTime: '2024-02-13T14:00:00.000Z',
            status: 'CANCELLED',
            notes: 'Time conflict',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            tenantId: 3,
            serviceId: 3,
            staffId: 3,
            customerId: null,
            guestName: 'Sophia Martinez',
            guestEmail: 'sophia@email.com',
            guestPhone: '+1555000007',
            startTime: '2024-02-10T10:00:00.000Z',
            endTime: '2024-02-10T11:00:00.000Z',
            status: 'COMPLETED',
            notes: 'Successful consultation',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            tenantId: 2,
            serviceId: 2,
            staffId: 2,
            customerId: null,
            guestName: 'James Anderson',
            guestEmail: 'james@email.com',
            guestPhone: '+1555000008',
            startTime: '2024-02-09T15:00:00.000Z',
            endTime: '2024-02-09T16:30:00.000Z',
            status: 'COMPLETED',
            notes: 'Very satisfied customer',
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
    ];

    await db.insert(appointments).values(sampleAppointments);
    
    console.log('✅ Appointments seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});