import { db } from '@/db';
import { services } from '@/db/schema';

async function main() {
    const sampleServices = [
        // Tenant 1: Beautiful Hair Salon
        {
            tenantId: 1,
            nameEn: 'Haircut',
            nameFr: 'Coupe de cheveux',
            nameAr: 'قص الشعر',
            descriptionEn: 'Professional haircut service tailored to your style preferences. Includes consultation, shampoo, cut, and blow-dry.',
            descriptionFr: 'Service de coupe de cheveux professionnel adapté à vos préférences de style. Comprend consultation, shampooing, coupe et brushing.',
            descriptionAr: 'خدمة قص شعر احترافية مصممة حسب تفضيلات أسلوبك. تشمل الاستشارة والشامبو والقص والتجفيف.',
            duration: 60,
            price: 45.00,
            isActive: true,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            tenantId: 1,
            nameEn: 'Hair Coloring',
            nameFr: 'Coloration',
            nameAr: 'صبغ الشعر',
            descriptionEn: 'Complete hair coloring service using premium products. Includes color consultation, application, processing, and styling.',
            descriptionFr: 'Service complet de coloration des cheveux utilisant des produits haut de gamme. Comprend consultation couleur, application, traitement et coiffage.',
            descriptionAr: 'خدمة صبغ شعر كاملة باستخدام منتجات متميزة. تشمل استشارة اللون والتطبيق والمعالجة والتصفيف.',
            duration: 120,
            price: 120.00,
            isActive: true,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            tenantId: 1,
            nameEn: 'Styling',
            nameFr: 'Coiffage',
            nameAr: 'تصفيف الشعر',
            descriptionEn: 'Expert hair styling for special occasions or everyday elegance. Includes blow-dry, straightening, or curling as desired.',
            descriptionFr: 'Coiffage expert pour occasions spéciales ou élégance quotidienne. Comprend brushing, lissage ou bouclage selon vos souhaits.',
            descriptionAr: 'تصفيف شعر احترافي للمناسبات الخاصة أو الأناقة اليومية. يشمل التجفيف أو التمليس أو التجعيد حسب الرغبة.',
            duration: 45,
            price: 35.00,
            isActive: true,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            tenantId: 1,
            nameEn: 'Deep Conditioning Treatment',
            nameFr: 'Soin revitalisant profond',
            nameAr: 'علاج ترطيب عميق',
            descriptionEn: 'Intensive conditioning treatment to restore moisture and shine to damaged or dry hair. Includes scalp massage.',
            descriptionFr: 'Traitement revitalisant intensif pour restaurer hydratation et brillance aux cheveux abîmés ou secs. Comprend massage du cuir chevelu.',
            descriptionAr: 'علاج ترطيب مكثف لاستعادة الرطوبة واللمعان للشعر التالف أو الجاف. يشمل تدليك فروة الرأس.',
            duration: 30,
            price: 55.00,
            isActive: true,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        // Tenant 2: Relaxation Spa
        {
            tenantId: 2,
            nameEn: 'Swedish Massage',
            nameFr: 'Massage suédois',
            nameAr: 'مساج سويدي',
            descriptionEn: 'Traditional Swedish massage technique focusing on relaxation and stress relief. Uses long, flowing strokes to ease muscle tension.',
            descriptionFr: 'Technique traditionnelle de massage suédois axée sur la relaxation et le soulagement du stress. Utilise des mouvements longs et fluides pour soulager les tensions musculaires.',
            descriptionAr: 'تقنية المساج السويدي التقليدية التي تركز على الاسترخاء وتخفيف التوتر. يستخدم حركات طويلة ومتدفقة لتخفيف توتر العضلات.',
            duration: 90,
            price: 95.00,
            isActive: true,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            tenantId: 2,
            nameEn: 'Deep Tissue Massage',
            nameFr: 'Massage en profondeur',
            nameAr: 'مساج الأنسجة العميقة',
            descriptionEn: 'Therapeutic massage targeting deeper muscle layers to relieve chronic pain and tension. Ideal for athletes and active individuals.',
            descriptionFr: 'Massage thérapeutique ciblant les couches musculaires plus profondes pour soulager douleur chronique et tension. Idéal pour athlètes et personnes actives.',
            descriptionAr: 'مساج علاجي يستهدف طبقات العضلات العميقة لتخفيف الألم المزمن والتوتر. مثالي للرياضيين والأشخاص النشطين.',
            duration: 60,
            price: 85.00,
            isActive: true,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            tenantId: 2,
            nameEn: 'Facial Treatment',
            nameFr: 'Soin du visage',
            nameAr: 'علاج الوجه',
            descriptionEn: 'Rejuvenating facial treatment including cleansing, exfoliation, mask, and moisturizing. Customized to your skin type.',
            descriptionFr: 'Soin du visage rajeunissant comprenant nettoyage, exfoliation, masque et hydratation. Personnalisé selon votre type de peau.',
            descriptionAr: 'علاج وجه منعش يشمل التنظيف والتقشير والقناع والترطيب. مخصص حسب نوع بشرتك.',
            duration: 75,
            price: 70.00,
            isActive: true,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            tenantId: 2,
            nameEn: 'Hot Stone Therapy',
            nameFr: 'Thérapie aux pierres chaudes',
            nameAr: 'علاج الحجارة الساخنة',
            descriptionEn: 'Relaxing massage using heated smooth stones to ease muscle stiffness and improve circulation. Deeply calming experience.',
            descriptionFr: 'Massage relaxant utilisant des pierres lisses chauffées pour soulager raideur musculaire et améliorer circulation. Expérience profondément apaisante.',
            descriptionAr: 'مساج مريح باستخدام حجارة ملساء ساخنة لتخفيف تصلب العضلات وتحسين الدورة الدموية. تجربة مهدئة بعمق.',
            duration: 90,
            price: 110.00,
            isActive: true,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        // Tenant 3: Health & Wellness Clinic
        {
            tenantId: 3,
            nameEn: 'General Consultation',
            nameFr: 'Consultation générale',
            nameAr: 'استشارة عامة',
            descriptionEn: 'Comprehensive health consultation with our medical professionals. Includes assessment, diagnosis, and treatment recommendations.',
            descriptionFr: 'Consultation santé complète avec nos professionnels médicaux. Comprend évaluation, diagnostic et recommandations de traitement.',
            descriptionAr: 'استشارة صحية شاملة مع متخصصينا الطبيين. تشمل التقييم والتشخيص وتوصيات العلاج.',
            duration: 30,
            price: 80.00,
            isActive: true,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            tenantId: 3,
            nameEn: 'Physical Therapy',
            nameFr: 'Physiothérapie',
            nameAr: 'علاج طبيعي',
            descriptionEn: 'Professional physical therapy session to rehabilitate injuries and improve mobility. Includes exercises and manual therapy.',
            descriptionFr: 'Séance de physiothérapie professionnelle pour réhabiliter blessures et améliorer mobilité. Comprend exercices et thérapie manuelle.',
            descriptionAr: 'جلسة علاج طبيعي احترافية لإعادة تأهيل الإصابات وتحسين الحركة. تشمل التمارين والعلاج اليدوي.',
            duration: 60,
            price: 65.00,
            isActive: true,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            tenantId: 3,
            nameEn: 'Wellness Checkup',
            nameFr: 'Bilan de santé',
            nameAr: 'فحص صحي',
            descriptionEn: 'Complete wellness checkup including vital signs, health screening, and personalized wellness recommendations.',
            descriptionFr: 'Bilan de santé complet incluant signes vitaux, dépistage santé et recommandations bien-être personnalisées.',
            descriptionAr: 'فحص صحي كامل يشمل العلامات الحيوية والفحص الصحي وتوصيات العافية الشخصية.',
            duration: 45,
            price: 100.00,
            isActive: true,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            tenantId: 3,
            nameEn: 'Nutrition Counseling',
            nameFr: 'Conseil nutritionnel',
            nameAr: 'استشارة تغذية',
            descriptionEn: 'Expert nutrition counseling to develop personalized meal plans and dietary strategies for optimal health.',
            descriptionFr: 'Conseil nutritionnel expert pour développer plans alimentaires personnalisés et stratégies diététiques pour santé optimale.',
            descriptionAr: 'استشارة تغذية متخصصة لتطوير خطط وجبات شخصية واستراتيجيات غذائية للصحة المثلى.',
            duration: 45,
            price: 75.00,
            isActive: true,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
    ];

    await db.insert(services).values(sampleServices);
    
    console.log('✅ Services seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});